version: "3.6"
services:
  express:
    build:
      context: ./express
      dockerfile: DockerfileProd
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - "postgres"
    environment:
      TOKEN_KEY: ${JWT_SECRET_KEY}
      PG_PASSWORD: ${POSTGRES_PW}

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgrespassword

  hasura:
    image: hasura/graphql-engine:v2.0.9
    depends_on:
      - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key": "thisisareallylongkeyitneedstobeatleastthirtytwocharactersaccordingtohasura"}'

  vue:
    build:
      context: ./vue
      dockerfile: DockerfileProd
    volumes:
      - /usr/src/app/node_modules
      - vue_static:/usr/src/app/dist
    depends_on:
      - "hasura"

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - vue_static:/srv
    depends_on:
      - "vue"
      - "express"
volumes:
  db_data:
  caddy_data:
    external: true
  caddy_config:
  vue_static:
